config/routes.rb
Rails.application.routes.draw do



  
  namespace :api do
    namespace :v1 do
       resources  :orders
   
       resources  :carts do
          post '/insert'=>'carts#insert', on: :collection
          post '/add_quantity'=>'carts#add_quantity',on: :collection
          post '/remove_quantity'=>'carts#remove_quantity',on: :collection
           post '/remove_item'=>'carts#remove_item',on: :collection

        end
       resources  :instruments
       resources  :ordered_items
       resources  :payments
      

       # scope  'cart/add/' do
       #    get "instruments/:id", to: ""
       # end
    end
  end
  
   use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :customers
  resources :sellers
  resources :ordered_items
  resources :wishlist do
    post '/insert' =>'wishlist#insert', on: :collection
  end
  resources :orders 
    resources :payments
  
  resources :line_items do
    get :add_quantity, on: :member
    get :remove_quantity, on: :member
  end
  resources :carts
  resources :instruments
  get 'search',to:"instruments#search"
  #get 'addquantity',to:"line_items#add_quantity"
  devise_for :users,controllers:{
    registrations: 'registrations'
  }
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  root 'instruments#index'
  delete 'instruments/:id'=>"instrument#destroy"
  # delete 'logout'  => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    
    #before_create :check_cart_has_line_items
	has_many :ordered_items
	has_many:instruments, through: :ordered_items
    has_one :payment
    accepts_nested_attributes_for :payment
    attr_accessor :skip_payment_card_number_validation
	belongs_to :user
	belongs_to :cart

	validates :address, :contact_number, presence: true
	validates :address, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud. "}
	validates :contact_number, numericality: {only_integer: true}
	validates :contact_number,length: {minimum: 10, maximum: 10}
    
	def total_price
    ordered_items.to_a.sum { |item| item.total_price }
  end

  private
 

  def check_cart_has_line_items
     if cart.line_items.count <= 0
     	errors.add(:base, "You dont have any items in your cart")
      throw :abort
  end
end


   
end
	

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < Api::V1::ApiController
  before_action :set_order, only: %i[ show update destroy ]
  
  before_action :acc_type_is_seller?
  before_action :doorkeeper_authorize!
  def index
    @orders = current_user.orders.all
    render json: @orders, status: 200
  end

  def show
    @order=Order.find(params[:id])
    if current_user.orders.include?(@order)
      render json: {message: "Your order items",order: @order,ordered_items:@order.ordered_items}, status: 200

   else
    render json: {
      error: "Order not found"
    }, status:404
   end
  end

  def create
  if order_params[:payment_method]=="CashOnDelievery"

    @order=Order.new(order_params)
    @order.user_id = current_user.id
    @order.cart=current_user.cart
     @order.save
     
        current_user.cart.line_items.each do |line_item|
        
          @order.ordered_items.create!(         
             instrument_id: line_item.instrument_id,
             quantity:   line_item.quantity 
          )
        end
        
         if @order.save
            render json: @order , status: 201
           else
         render json: {
         message: "Order not created"
        } , status: 422
      end
          
    
  else

  @order = Order.new(order_payment_params)
  @order.user_id = current_user.id
  @payment = @order.payment

  @payment.user_id = current_user.id
  
  @order.cart_id=current_user.cart_id

  if @order.save
            render json: {message: "Order #{@order.id } is created successfully"} , status: 201
           else
         render json: {
         message: "Order not created"
        } , status: 422
   end
  
        current_user.cart.line_items.each do |line_item|
       
          @order.ordered_items.create!(         
             instrument_id: line_item.instrument_id,
             quantity:   line_item.quantity 
          )
        end
          @order.save

  @payment.order_id=@order.id
  @payment.pay_amount = @order.total_price
  
  @payment.save 
    @order.save  
    end   
  end

  def update
    @order= Order.find_by(id: params[:id])
    if current_user.orders.include?(@order)
      @order.update(update_params)
      render json: {message:"Order #{@order.id} record updated Succesfully"}
    else
      render json: {
        error: "Order not found"
      },status: 404
    end
     
  end


  private
    
    def set_order
      @order = Order.find(params[:id])
    rescue
    render json: "Order not found", status: :not_found
    end
    def acc_type_is_seller?
       if current_user.accountable_type == "Seller"
         render json: {error: "You are not allowed to do this action"},status:403
       end
    end

    
    def update_params
      params.require(:order).permit(:address,:contact_number,:order_status)
    end

    def order_payment_params
      params.require(:order).permit(:address,:contact_number,:payment_method,payment_attributes: [:card_number,:expiry_month,:expiry_year,:cvv,:name_on_the_card])
    end

    def order_params
      params.require(:order).permit(:address,:contact_number,:payment_method)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
   before_action :acc_type_is_seller?, only: [:edit, :new , :index, :show, :create  , :destroy]
  

  def index
    @orders = current_user.orders.all
  end


  def show
    @order=Order.find(params[:id])
  end

 
  def new
    @order = Order.new
    @order.build_payment
    
  end

 
  def edit
  end

 
  def create
  if order_params[:payment_method]=="CashOnDelievery"

    @order=Order.new(order_params)
    @order.user = current_user
      @order.cart=current_user.cart
     @order.save

  
        current_user.cart.line_items.each do |line_item|
          
          @order.ordered_items.create!(         
             instrument_id: line_item.instrument_id,
             quantity:   line_item.quantity 
          )
        end
          @order.save
  else

  @order = Order.new(order_payment_params)
  @order.user = current_user
  @payment = @order.payment
  @payment.user = current_user
  @order.cart=current_user.cart
  @order.save

  
        current_user.cart.line_items.each do |line_item|
          
          @order.ordered_items.create!(         
             instrument_id: line_item.instrument_id,
             quantity:   line_item.quantity 
          )
        end
          @order.save

  @payment.order_id=@order.id
  @payment.pay_amount = @order.total_price

  @payment.save 
    @order.save  
    end   
  current_user.cart.line_items.destroy_all
  # Cart.destroy(session[:cart_id])
  # session[:cart_id] = nil

    redirect_to order_path(@order)
  end


 
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
      # p "ookkk"

      @order.order_status="cancelled"
      @order.save
      # @order.ordered_items.destroy_all
      @order.payment&.destroy
      # @order.destroy
      # @order.save

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    
    def set_order
      @order = Order.find(params[:id])
    end

  
    def order_payment_params
      params.require(:order).permit(:address,:contact_number,:payment_method,payment_attributes: [:card_number,:expiry_month,:expiry_year,:cvv,:name_on_the_card])
    end

    def order_params
      params.require(:order).permit(:address,:contact_number,:payment_method)
    end

    def acc_type_is_seller?
       if current_user.accountable_type == "Seller"
         redirect_to root_path, notice: "You are logged in as Seller"
       end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with model: @order, local: true do |f| %>
  <div style="margin-left: 350px;margin-top: 20px;">
    <p>
    <h4 class="title"> Necessary details to place your order</h4> 
  </p>
  </div>
  <div style="margin-left: 450px; margin-top: 25px;">
  <p class="f4">
    <%= f.label :contact_number %><br>
    <%= f.text_area :contact_number %>
  </p>
  <p class="f4">
    <%= f.label :Delivery_address %><br>
    <%= f.text_area :address %>
  </p>
  <p class="f4">
    <%= f.label :payment_method %><br>
    <%= f.select :payment_method, [["CashOnDelievery", "CashOnDelievery"], ["DebitOrCredit", "DebitOrCredit"]] %>
  </p>

<br>
  <div id="cod">
  <p>
    <%= f.submit :Place_order , class: 'button is-warning'%>
    <%#= link_to 'SUBMIT',order_path, class:'button is-light' %>
  </p>
</div>
  <br>
  <div id="pay">
  <h1 class="f4 title">Payment via debit/credit</h1>

    <%= f.fields_for :payment do |payments_form| %>
        <p class="f4">
    <%= payments_form.label :card_number%><br>
    <%= payments_form.text_area :card_number %>
  </p>
  <p class="f4">
    <%= payments_form.label :expiry_month %><br>
    <%= payments_form.text_area :expiry_month %>
  </p>
  <p class="f4">
    <%= payments_form.label :expiry_year %><br>
    <%= payments_form.text_area :expiry_year %>
  </p>
  <p class="f4">
    <%= payments_form.label :cvv %><br>
    <%= payments_form.text_area :cvv%>
  </p>
  <p class="f4">
    <%= payments_form.label :name_on_the_card %><br>
    <%= payments_form.text_area :name_on_the_card %>
  </p>
  <p>
    

    <% end %>
<%= f.submit :Place_order , class: 'button is-warning'%>
  <!-- <div class="form-inputs">
  </div>
  <div class="form-actions">
    <%#= f.button :submit %>
  </div> -->
<%end %>
</div>
</div>

<br>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js">
  
</script>
<script>
  $(document).ready(function(){
     $("#pay").hide();
    $("#cod").show();


});
  $("#order_payment_method").change(function(e){
    
    
    if ($('#order_payment_method').val()=="CashOnDelievery"){
    $("#pay").hide();
    $("#cod").show();
  }else{
    $("#pay").show();
    $("#cod").hide();
  }
  });

  
 
</script>


<%#= link_to 'Payment-debit/credit',new_order_payment_path(@order),class: "button is-danger" %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', carts_path %>
<h1>Payment via debit/credit</h1>

    <%= f.fields_for :payment do |payments_form| %>
        <p>
    <%= payments_form.label :card_number%><br>
    <%= payments_form.text_area :card_number %>
  </p>
  <p>
    <%= payments_form.label :expiry_month %><br>
    <%= payments_form.text_area :expiry_month %>
  </p>
  <p>
    <%= payments_form.label :expiry_year %><br>
    <%= payments_form.text_area :expiry_year %>
  </p>
  <p>
    <%= payments_form.label :cvv %><br>
    <%= payments_form.text_area :cvv%>
  </p>
  <p>
    <%= payments_form.label :name_on_the_card %><br>
    <%= payments_form.text_area :name_on_the_card %>
  </p>
  <p>
    

    <% end %>
    <%= f.submit :Place_order , class: 'button is-warning'%>
  <!-- <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%#= f.button :submit %>
  </div> -->
<%end %>

app/views/orders/index.html.erb
<section class="section">
<% @orders.each do |order| %>
<strong class="f4"> <%="Ordered on :"%><%=order.created_at%></strong>
<br>
<br>
<div class="box">
<%order.ordered_items.each do |ordered_item|%>
  <div class="columns align-items-center">
  <div class="column is-1">
    <%= ordered_item.quantity %>
  </div>
  <div class="column is-2">
    <figure class="is-128x128 image">
      <%= image_tag(ordered_item.instrument.image_url(:thumb)) %>
    </figure>
  </div>
  <div class="column is-9">
    <strong><%= ordered_item.instrument.title %></strong>
    <div class="columns align-items-center">
      <div class="content column is-9">
        <%= truncate(ordered_item.instrument.description, length: 140) %>
        <br>
        <%=ordered_item.created_at%>
        <br>
       <strong> <%="Delivery address:"%></strong>
        <br>
         <%=order.address%>
        
        <br>
        <%=order.contact_number%>
       
      
      </div>
      <div class="column is-3 has-text-right">
        <strong class="f4"><%= number_to_currency(ordered_item.total_price) %></strong>
        
      </div>

    </div>
  </div>
</div>
<br>
      <br>
      <br>
      <br>
       <%end%>
       <%if order.order_status == "ordered"%>

  <%= button_to 'Cancel order',order_path(order.id), method: :delete, data: { confirm: "Are you sure? " }, class: "button is-small mb4" %>
  <%elsif order.order_status == "delievered"%>
  <button class="button"><%="Delievered"%></button>
  <%else%>
  <button class="button"><%="Cancelled"%></button>
  <%end%>
     </div>
      
    <% end %>

</section>

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

<%#= link_to 'Back', carts_path %>

app/views/orders/show.html.erb
<!-- <p id="notice"><%#= notice %></p>

<%#= link_to 'Edit', edit_order_path(@order) %> |
<%#= link_to 'Back', orders_path %> -->
<!-- <h2>THANK YOU FOR SHOPPING</h2>
     <p>Your Order has been placed successfully</p> 
<div class="keep-shopping pv1 mt4 has-text-right">
  <%#= link_to 'Keep Shopping', instruments_path, class: 'button is-warning' %>
</div> -->



<section class="section">
<div style="margin-left: 350px;margin-top: 20px;">
    <p>
    <h4 class="title"> Your order details</h4> 
  </p>
  </div>
<%@order.ordered_items.each do |ordered_item|%>
  <div class="columns align-items-center">
  <div class="column is-1">
    <%= ordered_item.quantity %>
  </div>
  <div class="column is-2">
    <figure class="is-128x128 image">
      <%= image_tag(ordered_item.instrument.image_url(:thumb)) %>
    </figure>
  </div>
  <div class="column is-9">
    <strong><%= ordered_item.instrument.title %></strong>
    <div class="columns align-items-center">
      <div class="content column is-9">
        <%= truncate(ordered_item.instrument.description, length: 140) %>
        <br>
        <%=ordered_item.created_at%>
        <br>
       
        <strong> <%="Delivery address:"%></strong>
     
        <br>
         <%=@order.address%>
        
        <br>
        <%=@order.contact_number%>
       
      
      </div>
      <div class="column is-3 has-text-right">
        <strong class="f4"><%= number_to_currency(ordered_item.total_price) %></strong>
        
</div>
    </div>
  </div>
</div>
<br>
      <br>
      <br>
      <br>
       <%end%>
       
      
  

</section>