config/routes.rb
Rails.application.routes.draw do



  
  namespace :api do
    namespace :v1 do
       resources  :orders
   
       resources  :carts do
          post '/insert'=>'carts#insert', on: :collection
          post '/add_quantity'=>'carts#add_quantity',on: :collection
          post '/remove_quantity'=>'carts#remove_quantity',on: :collection
           post '/remove_item'=>'carts#remove_item',on: :collection

        end
       resources  :instruments
       resources  :ordered_items
       resources  :payments
      

       # scope  'cart/add/' do
       #    get "instruments/:id", to: ""
       # end
    end
  end
  
   use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :customers
  resources :sellers
  resources :ordered_items
  resources :wishlist do
    post '/insert' =>'wishlist#insert', on: :collection
  end
  resources :orders 
    resources :payments
  
  resources :line_items do
    get :add_quantity, on: :member
    get :remove_quantity, on: :member
  end
  resources :carts
  resources :instruments
  get 'search',to:"instruments#search"
  #get 'addquantity',to:"line_items#add_quantity"
  devise_for :users,controllers:{
    registrations: 'registrations'
  }
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  root 'instruments#index'
  delete 'instruments/:id'=>"instrument#destroy"
  # delete 'logout'  => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
	belongs_to :user
	belongs_to :order, optional: true
	#before_validation :check_payment_method,on: :create
	validates :card_number, :expiry_month,:expiry_year,:name_on_the_card,:cvv, presence: true
	validates :card_number, numericality: {only_integer: true}
	validates :card_number,length: {minimum: 12, maximum: 12}
	validates :expiry_month, numericality: {only_integer: true, greater_than:00, less_than:13}
	validates :expiry_month,length: {minimum: 2, maximum: 2}
	validates :expiry_year, numericality: {only_integer: true,greater_than: 2022}
	validates :expiry_year,length: {minimum: 4, maximum: 4}
	validates :cvv, numericality: {only_integer: true}
	validates :cvv,length: {minimum: 3, maximum: 3}
    

    private
    def check_payment_method
    	if order.payment_method=="CashOnDelievery" 
    		Payment.save(validate: false)
    	end
    end

end

app/controllers/api/v1/payments_controller.rb
class Api::V1::PaymentsController < Api::V1::ApiController
  before_action :doorkeeper_authorize!
  before_action :acc_type_is_seller?

  def index
    @payments = current_user.payments.all
    render json: @payments, status: 200
  end
  private

  def acc_type_is_seller?
       if current_user.accountable_type == "Seller"
         render json: {error: "You are not allowed to do this action"},status:403
       end
  end

  
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[ show edit update destroy ]
  before_action :acc_type_is_seller?, only: [:edit, :new , :index, :show, :create  , :destroy]
  
  def index
    @payments = Payment.all
    
  end

  
  def show
  end

 
  def new
    @payment = Payment.new
    
  end

 
  def edit
  end

  def create
    @order = Order.find params[:order_id]
    
    @payment = current_user.payments.build(payment_params)
   
    @payment.order_id=@order.id
     @payment.pay_amount=@order.total_price
    @payment.save
    #p @payment
    respond_to do |format|
      if @payment.save
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
   
    def set_payment
      @payment = Payment.find(params[:id])
    end

   
    def payment_params
     params.require(:payment).permit(:card_number, :expiry_month, :expiry_year, :name_on_the_card, :cvv, :title)
    end
    def acc_type_is_seller?
       if current_user.accountable_type == "Seller"
         redirect_to root_path, notice: "You are logged in as Seller"
       end
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<!-- <%#= simple_form_for(@payment) do |f| %>
  <%#= f.error_notification %>
  <%#= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%#= f.button :submit %>
  </div>
<%# end %>
 -->



 <%#= form_with model: @payment, local: true do |f| %>
  <%= simple_form_for(@payment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
 
  <p>
    <%= f.label :card_number%><br>
    <%= f.text_area :card_number %>
  </p>
  <p>
    <%= f.label :expiry_month %><br>
    <%= f.text_area :expiry_month %>
  </p>
  <p>
    <%= f.label :expiry_year %><br>
    <%= f.text_area :expiry_year %>
  </p>
  <p>
    <%= f.label :cvv %><br>
    <%= f.text_area :cvv%>
  </p>
  <p>
    <%= f.label :name_on_the_card %><br>
    <%= f.text_area :name_on_the_card %>
  </p>

 
  <p>
    <%= f.submit :Place_order , class: 'button is-warning'%>
    <%#= link_to 'SUBMIT',order_path, class:'button is-light' %>
  </p>
  <!-- <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%#= f.button :submit %>
  </div> -->
<%end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h2>THANK YOU FOR SHOPPING</h2>
     <p>Your Order has been placed successfully</p> 
<div class="keep-shopping pv1 mt4 has-text-right">
  <%= link_to 'Keep Shopping', instruments_path, class: 'button is-warning' %>
</div>

app/views/payments/new.html.erb
<strong><h1>New Payment</h1></strong>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>