config/routes.rb
Rails.application.routes.draw do



  
  namespace :api do
    namespace :v1 do
       resources  :orders
   
       resources  :carts do
          post '/insert'=>'carts#insert', on: :collection
          post '/add_quantity'=>'carts#add_quantity',on: :collection
          post '/remove_quantity'=>'carts#remove_quantity',on: :collection
           post '/remove_item'=>'carts#remove_item',on: :collection

        end
       resources  :instruments
       resources  :ordered_items
       resources  :payments
      

       # scope  'cart/add/' do
       #    get "instruments/:id", to: ""
       # end
    end
  end
  
   use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :customers
  resources :sellers
  resources :ordered_items
  resources :wishlist do
    post '/insert' =>'wishlist#insert', on: :collection
  end
  resources :orders 
    resources :payments
  
  resources :line_items do
    get :add_quantity, on: :member
    get :remove_quantity, on: :member
  end
  resources :carts
  resources :instruments
  get 'search',to:"instruments#search"
  #get 'addquantity',to:"line_items#add_quantity"
  devise_for :users,controllers:{
    registrations: 'registrations'
  }
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  root 'instruments#index'
  delete 'instruments/:id'=>"instrument#destroy"
  # delete 'logout'  => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  before_destroy :not_refereced_by_any_line_item
  after_validation :normalize_title, on: :create
  belongs_to :user, optional: true
  has_many :line_items
  has_many :carts, through: :line_items
  has_many :ordered_items, dependent: :destroy
  has_many :orders, through: :ordered_items
  has_and_belongs_to_many :wishlists, dependent: :destroy
  
  mount_uploader :image, ImageUploader
  serialize :image, JSON 

  validates :title, :brand, :price, :model,:color, presence: true
  validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud. "}
  validates :title, length: { maximum: 30, too_long: "%{count} characters is the maximum aloud. "}
  validates :price, length: { maximum: 7 }
  validates :price, numericality: {only_decimal: true, greater_than: 0}
  #validates :quantity, numericality: {only_integer: true, greater_than: 0}

  BRAND = %w{ Fender Gibson Epiphone ESP Martin Dean Taylor Jackson PRS  Ibanez Charvel Washburn }
  COLOR = %w{ Black White Navy Blue Red Clear Satin Yellow Seafoam }
  CONDITION = %w{ New Excellent Mint Used Fair Poor }

  private

  def not_refereced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end

  def normalize_title
  self.title = title.upcase
  end

end

app/controllers/api/v1/instruments_controller.rb
class Api::V1::InstrumentsController < Api::V1::ApiController
  before_action :set_instrument, only: [:show, :update, :destroy]
  before_action :doorkeeper_authorize!
 
   before_action :acc_type_is_customer?, only: [:update, :create,:destroy]
  def index
    if current_user.accountable_type=="Customer"
    @instruments = Instrument.all.order("created_at desc")
  else
    @instruments=current_user.instruments
  end
    render json: {Instruments:@instruments}, status: 200
    
  end

  def show
    @instrument=Instrument.find_by(id: params[:id])
    if current_user.accountable_type=="Seller"
      if current_user.instruments.exclude?(@instrument) 
        render json: { error: "You are not allowed to view this instrument"}, status: 403
      else
        render json: @instrument, status: 200
      end
    else
    if @instrument

      render json: @instrument, status: 200

   else
    render json: {
      error: "Instrument not found"
    } , status: 404
   end
  end
  end

  def create
    
    @instrument = current_user.instruments.create(instrument_params)
    
    if @instrument.save

      render json: @instrument , status: 201
    else
      render json: {
        message: "Instrument not created"
      } , status: 422
    end
  end

  def update
    @instrument= Instrument.find_by(id: params[:id])
    if current_user.accountable_type=="Seller"
     if current_user.instruments.exclude?(@instrument) 
        render json: { error: "You are not allowed to do this update"}, status: 403
        return
      end
    end
    if @instrument
      @instrument.update(instrument_params)
      render json: {
        message: "Instrument with id #{@instrument.id } is updated successfully"
      } , status: 200
    else
      render json: {
        error: "Instrument not found"
      } , status: 404
    end
  end

  def destroy
    @instrument= Instrument.find_by(id: params[:id])
    if current_user.accountable_type=="Seller"
     if current_user.instruments.exclude?(@instrument) 
        render json: { error: "You are not allowed to do this action"}, status: 403
        return
      end
    end
    if @instrument
      @instrument.destroy
      render json: {
        message: "Instrument is destroyed successfully"
      } , status: 204
    else
      render json: {
        error: "Instrument not found"
      } , status: 404
    end
  end

  private
  def set_instrument
      @instrument = Instrument.find(params[:id])
    rescue
    render json: "Instrument not found", status: :not_found
    
    end

     def acc_type_is_customer?
       if current_user.accountable_type == "Customer"
         render json: {error: "You are not allowed to do this action"},status:403
       end
    end

    
     


    
    def instrument_params
      params.require(:instrument).permit(:brand, :model, :description, :condition,:color, :title, :price,:quantity, :user_id)
    end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  before_action :acc_type_is_customer?, only: [:edit, :new, :create ]

  

 
  def index
    @instruments = Instrument.all.order("created_at desc")
  end


  def search
    @instruments=Instrument.where("title LIKE ?","%"+params[:q]+"%")
  end
                                        

  
  def show
    
  end

  



  
  def new
    @instrument = current_user.instruments.build
  end

  def edit
  end

  
  def create
    @instrument = current_user.instruments.build(instrument_params)
    respond_to do |format|
      if @instrument.save
        format.html { redirect_to instruments_url, notice: 'Instrument was successfully created.' }
        format.json { render :show, status: :created, location: @instrument }
      else
        
        format.html { render :new }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
       
        format.html { redirect_to @instrument, notice: 'Instrument was successfully updated.' }
        format.json { render :show, status: :ok, location: @instrument }
      else
        format.html { render :edit }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @instrument.destroy
    respond_to do |format|
      format.html { redirect_to instruments_url, notice: 'Instrument was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

   
    def instrument_params
      params.require(:instrument).permit(:brand, :model, :description, :condition, :finish, :title, :price, :image, :quantity, :color)
    end

    def acc_type_is_customer?
       if current_user.accountable_type == "Customer"
         redirect_to root_path
       end
    end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper

  def instrument_author(instrument)
    user_signed_in? && current_user.id == instrument.user_id
  end

end

app/views/instruments/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @instrument, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column">
            <div class="control">
              <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        </div>

        <div class="field">
          <div class="control">
            <%= f.input :model, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.input :quantity, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="columns">
          <div class="field column is-4">
            <div class="control">
              <label class="label">Brand</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :brand, collection: Instrument::BRAND, prompt: "Select brand" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-4">
            <div class="control">
              <label class="label">Color</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :color, collection: Instrument::COLOR, prompt: "Select color" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>
           

          <div class="field column is-4">
            <div class="control">
              <label class="label">Condition</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :condition, collection: Instrument::CONDITION, prompt: "Select condition" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>
         </div>

        <div class="field">
          <div class="control">
            <label class="label">Add images</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input instrument-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', instruments_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/instruments/edit.html.erb
<% content_for :header do %>
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing Instrument
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', instrument: @instrument %>
</div>

app/views/instruments/index.html.erb
<% content_for :header do %>
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <%if user_signed_in? %>
  <% if current_user.accountable_type=="Seller"%>
  <h1 class="title">
        YOUR PRODUCTS!!
      </h1>

      
      <%else%>
      <h1 class="title">
        What's new!!
      </h1>
      <%end%>
      <%else%>
      <h1 class="title">
        What's new!!
      </h1>
      <%end%>
    </div>
  </div>
</section>
<%end%>

<div class="instrument-index-grid pt4">
  <%if user_signed_in? %>
  <% if current_user.accountable_type=="Seller"%>
  <% current_user.instruments.each do |instrument| %>

    <div class="instrument border-light">
      <div class="instrument-thumb">
      <%= link_to image_tag(instrument.image_url(:thumb)), instrument %>

      <% if instrument.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= instrument.condition %></span>
        </div>
      <% end %>
    </div>
  

    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to instrument.title, instrument %></h3>

      

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(instrument.price) %></p>
       
      <%#elsif current_user.accountable_type=="Seller"%>
      
      

      </div>
      <% if instrument_author(instrument) %>
         <%= link_to 'Edit', edit_instrument_path(instrument), class: "button is-small" %>
         <%= link_to 'Delete', instrument, method: :delete, data: { turbolinks_method: :delete }, class: "button is-small" %>
      <% end %>
  </div>

  <% end %>
</div>
     
  
      <%else%>
      <% @instruments.each do |instrument| %>

    <div class="instrument border-light">
      <div class="instrument-thumb">
      <%= link_to image_tag(instrument.image_url(:thumb)), instrument %>

      <% if instrument.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= instrument.condition %></span>
        </div>
      <% end %>
    </div>
  

    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to instrument.title, instrument %></h3>

      <p class="has-text-gray fg pt1">Sold by <%= instrument.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(instrument.price) %></p>
       
      <%#elsif current_user.accountable_type=="Seller"%>
      
      

      </div>
  </div>
  <% end %>
</div>
       <%end %>
       <%else%>
       <% @instruments.each do |instrument| %>

    <div class="instrument border-light">
      <div class="instrument-thumb">
      <%= link_to image_tag(instrument.image_url(:thumb)), instrument %>

      <% if instrument.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= instrument.condition %></span>
        </div>
      <% end %>
    </div>
  

    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to instrument.title, instrument %></h3>

      <p class="has-text-gray fg pt1">Sold by <%= instrument.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(instrument.price) %></p>
       
      <%#elsif current_user.accountable_type=="Seller"%>
      
      

      </div>
  </div>
  <% end %>
</div>
      <%end%>
   
  

app/views/instruments/new.html.erb
<% content_for :header do %>
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Sell an Instrument
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', instrument: @instrument %>
</div>

app/views/instruments/search.html.erb
<h1> Search Results</h1>

<div class="instrument-index-grid pt4">
  <% @instruments.each do |instrument| %>

    <div class="instrument border-light">
      <div class="instrument-thumb">
      <%= link_to image_tag(instrument.image_url(:thumb)), instrument %>

      <% if instrument.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= instrument.condition %></span>
        </div>
      <% end %>
    </div>
  

    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to instrument.title, instrument %></h3>

      <p class="has-text-gray fg pt1">Sold by <%= instrument.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(instrument.price) %></p>

      <% if instrument_author(instrument) %>
         <%= link_to 'Edit', edit_instrument_path(instrument), class: "button is-small" %>
         <%= link_to 'Delete', instrument, method: :delete, data: { turbolinks_method: :delete }, class: "button is-small" %>
      <% end %>

    </div>
  </div>
  <% end %>
</div>

app/views/instruments/show.html.erb
<% content_for :body_class, 'bg-light' %>


<%if user_signed_in? && (current_user.accountable_type=="Seller" && not(instrument_author(@instrument)))%>
<h1> You are not allowed to view this product </h1>
<%else%>

<section class="section instrument-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @instrument.title %></h1>

      <ul class="pv1">
        <% if @instrument.brand? %>
        <li class="inline-block pr3"><%= @instrument.brand %></li>
        <% end %>

        <li class="inline-block pr3"><%= @instrument.model %></li>

        <% if @instrument.condition? %>
        <li class="inline-block pr3"><%= @instrument.condition %></li>
        <% end %>
      </ul>

      <div class="feature-image">
        <%= image_tag(@instrument.image_url(:default)) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Description</h3>
      <%= @instrument.description %>


      <h3 class="subtitle is-4 pt5">Product Specs</h3>

      <table class="table is-narrow">
        <% if @instrument.condition %>
        <tr>
          <td class="has-text-weight-bold">Condition:</td>
          <td><%= @instrument.condition %></td>
        </tr>
        <% end %>

        <% if @instrument.color %>
          <tr>
            <td class="has-text-weight-bold">Color:</td>
            <td><%= @instrument.color %></td>
          </tr>
        <% end %>

        <% if @instrument.brand %>
          <tr>
            <td class="has-text-weight-bold">Brand:</td>
            <td><%= @instrument.brand %></td>
          </tr>
        <% end %>

        <tr>
          <td class="has-text-weight-bold">Model:</td>
          <td><%= @instrument.model %></td>
        </tr>
        <tr>
          <td class="has-text-weight-bold">Quantity available:</td>
          <td><%= @instrument.quantity %></td>
        </tr>
      </table>
    </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@instrument.price) %></h4>
        <%if user_signed_in? && current_user.accountable_type=="Customer"%>
        <p class="has-text-centered mb4">Sold by <%= @instrument.user.name %></p>
        <%end%>
        <% if  user_signed_in? && @instrument.quantity>=1 && current_user.accountable_type=="Customer"%>
        <%= button_to 'Add to cart', line_items_path(instrument_id: @instrument), class: 'button is-warning add-to-cart' %> 
         <%end%>
        <br>
        <%if user_signed_in? && current_user.accountable_type=="Customer" && current_user.wishlist.instruments.exclude?(@instrument) && current_user.wishlist.present?%>
        <%= button_to 'Add to wishlist', insert_wishlist_index_path(instrument_id: @instrument), class: 'button is-warning add-to-cart' %> 
        <% end %>
       
      </div>
    </div>
  </div>

  <% if instrument_author(@instrument) %>
    <%= link_to 'Edit', edit_instrument_path(@instrument), class: 'button' %>
  <% end %>

</section>
<%end%>