config/routes.rb
Rails.application.routes.draw do



  
  namespace :api do
    namespace :v1 do
       resources  :orders
   
       resources  :carts do
          post '/insert'=>'carts#insert', on: :collection
          post '/add_quantity'=>'carts#add_quantity',on: :collection
          post '/remove_quantity'=>'carts#remove_quantity',on: :collection
           post '/remove_item'=>'carts#remove_item',on: :collection

        end
       resources  :instruments
       resources  :ordered_items
       resources  :payments
      

       # scope  'cart/add/' do
       #    get "instruments/:id", to: ""
       # end
    end
  end
  
   use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :customers
  resources :sellers
  resources :ordered_items
  resources :wishlist do
    post '/insert' =>'wishlist#insert', on: :collection
  end
  resources :orders 
    resources :payments
  
  resources :line_items do
    get :add_quantity, on: :member
    get :remove_quantity, on: :member
  end
  resources :carts
  resources :instruments
  get 'search',to:"instruments#search"
  #get 'addquantity',to:"line_items#add_quantity"
  devise_for :users,controllers:{
    registrations: 'registrations'
  }
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  root 'instruments#index'
  delete 'instruments/:id'=>"instrument#destroy"
  # delete 'logout'  => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :instruments, through: :line_items
  has_many :orders
  belongs_to :user
  def add_instrument(instrument)
    current_item = line_items.find_by(instrument_id: instrument.id)
    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(instrument_id: instrument.id, cart_id: id)

    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end


  
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_one:user, as: :accountable
	
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  before_destroy :not_refereced_by_any_line_item
  after_validation :normalize_title, on: :create
  belongs_to :user, optional: true
  has_many :line_items
  has_many :carts, through: :line_items
  has_many :ordered_items, dependent: :destroy
  has_many :orders, through: :ordered_items
  has_and_belongs_to_many :wishlists, dependent: :destroy
  
  mount_uploader :image, ImageUploader
  serialize :image, JSON 

  validates :title, :brand, :price, :model,:color, presence: true
  validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud. "}
  validates :title, length: { maximum: 30, too_long: "%{count} characters is the maximum aloud. "}
  validates :price, length: { maximum: 7 }
  validates :price, numericality: {only_decimal: true, greater_than: 0}
  #validates :quantity, numericality: {only_integer: true, greater_than: 0}

  BRAND = %w{ Fender Gibson Epiphone ESP Martin Dean Taylor Jackson PRS  Ibanez Charvel Washburn }
  COLOR = %w{ Black White Navy Blue Red Clear Satin Yellow Seafoam }
  CONDITION = %w{ New Excellent Mint Used Fair Poor }

  private

  def not_refereced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end

  def normalize_title
  self.title = title.upcase
  end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :instrument
  belongs_to :cart
 
  
  def total_price
    instrument.price.to_i * quantity.to_i
  end
  

 
end

app/models/order.rb
class Order < ApplicationRecord
    
    #before_create :check_cart_has_line_items
	has_many :ordered_items
	has_many:instruments, through: :ordered_items
    has_one :payment
    accepts_nested_attributes_for :payment
    attr_accessor :skip_payment_card_number_validation
	belongs_to :user
	belongs_to :cart

	validates :address, :contact_number, presence: true
	validates :address, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud. "}
	validates :contact_number, numericality: {only_integer: true}
	validates :contact_number,length: {minimum: 10, maximum: 10}
    
	def total_price
    ordered_items.to_a.sum { |item| item.total_price }
  end

  private
 

  def check_cart_has_line_items
     if cart.line_items.count <= 0
     	errors.add(:base, "You dont have any items in your cart")
      throw :abort
  end
end


   
end
	

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order
  belongs_to :instrument
  def total_price
    instrument.price.to_i * quantity.to_i
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
	belongs_to :user
	belongs_to :order, optional: true
	#before_validation :check_payment_method,on: :create
	validates :card_number, :expiry_month,:expiry_year,:name_on_the_card,:cvv, presence: true
	validates :card_number, numericality: {only_integer: true}
	validates :card_number,length: {minimum: 12, maximum: 12}
	validates :expiry_month, numericality: {only_integer: true, greater_than:00, less_than:13}
	validates :expiry_month,length: {minimum: 2, maximum: 2}
	validates :expiry_year, numericality: {only_integer: true,greater_than: 2022}
	validates :expiry_year,length: {minimum: 4, maximum: 4}
	validates :cvv, numericality: {only_integer: true}
	validates :cvv,length: {minimum: 3, maximum: 3}
    

    private
    def check_payment_method
    	if order.payment_method=="CashOnDelievery" 
    		Payment.save(validate: false)
    	end
    end

end

app/models/seller.rb
class Seller < ApplicationRecord
	has_one:user, as: :accountable
	
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :instruments
  has_many :orders
  has_many :payments
  has_one :cart
  has_one :wishlist

  validates_presence_of :password, :email
  
  belongs_to:accountable,polymorphic:true, inverse_of: :user

  scope :customer, -> { where(accountable_type: "Customer") }
  scope :seller, -> { where(accountable_type: "Seller") }
  

 

  


  ACCOUNTABLETYPE = %w{ seller customer }

   def self.authenticate(email, password)
    user = User.find_for_authentication(email: email)
    user&.valid_password?(password) ? user : nil
  end
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :user
	has_and_belongs_to_many :instruments, dependent: :destroy
end

app/helpers/carts_helper.rb
module CartsHelper
	
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/wishlist_helper.rb
module WishlistHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music Cart</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5">Music Cart</h1>
        <% end  %>


      <!-- search -->
      <div class="field column is-9 head">
        <form class="field column is-9" action="/search">
        
        <input class="input" name="q" type="text"  placeholder="Search" aria-label="Search" value=<%= params[:q] || "" %>>
        <button class= "button is-danger" type="submit">Search</button>

      </form>
      </div>
         



      <div class="navbar-burger burger" data-target="navbar">

        <span></span>
        <span></span>
        <span></span>
      </div>
       
    </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">

           <!-- <%#if total_cart_items %>
              <%#= link_to cart_path(@cart), class:"navbar-item button is-warning" do %>
              <span class="icon is-small">
                <i class="fa fa-shopping-cart"></i>
              </span>
              <span>Cart
                <%#= cart_count_over_one %>
                </span>
              <%#end %>
            <%# end %> 


 -->        
      
            
            <% if user_signed_in?  %>
            <%if current_user.accountable_type =="Customer"%>
             <p class="buttons">
               <button class="button is-warning">
            <span>
            <%= link_to 'My orders', orders_path  %>
           </span>
       </button>
           
           <button class="button is-warning">
            <span>

            <%= link_to 'Cart',@cart  %>
           
         </span>
       </button>
       <button class="button is-warning">
            <span>
            <%= link_to 'Wishlist',wishlist_path(current_user)  %>
            </span>
       </button>
          </p>
         
            <%elsif current_user.accountable_type =="Seller"%>
              <%= link_to 'Sell', new_instrument_path, class: "navbar-item button is-dark" %>
            <%end%>
              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>
            <% else %>

            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-warning" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-warning"%>

            <% end %>

            </div>
          </div>
        </div>
    </div>
  </nav>

  <%= yield(:header) %>

  <div class="container">

    <%= yield %>

  </div>

  </body>
</html>